# -*- coding: utf-8 -*-
"""Big Data 2 Working Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aaTRzrCLpu3BYY3csr2uQeyWZjm2AKgf
"""

!pip install zarr
!pip install torchmetrics

from google.colab import drive
drive.mount('/content/drive')

import sys
sys.path.append('/content/drive/MyDrive/Big Data 2')

import shutil
import zipfile
import os

# Copy zip file from Drive to Colab runtime
shutil.copy('/content/drive/MyDrive/Big Data 2/timematch_data.zip', '/content/')

# Unzip the file
with zipfile.ZipFile('/content/timematch_data.zip', 'r') as zip_ref:
   zip_ref.extractall('/content/')

# Create list of parcel IDs from .zarr directory names
data_dir = '/content/timematch_data/denmark/32VNH/2017/data'
parcel_ids_on_disk = []

for item in os.listdir(data_dir):
   if item.endswith('.zarr') and os.path.isdir(os.path.join(data_dir, item)):
       parcel_id = item.replace('.zarr', '')
       parcel_ids_on_disk.append(parcel_id)

print(f"Found {len(parcel_ids_on_disk)} parcel IDs: {parcel_ids_on_disk[:10]}...")  # Show first 10

# =============================================================================
# EXPERIMENT SETUP CELL
# =============================================================================

# Standard Library Imports
import os
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Scikit-learn
from sklearn.model_selection import KFold

# TorchMetrics
import torchmetrics

# Custom Module Imports
import sources.data_utils as data_utils
import sources.model   as model
import sources.engine as engine



# =============================================================================
# CONSTANTS AND CONFIGURATIONS
# =============================================================================


DATA_ROOT = "timematch_data/denmark/32VNH/2017"
META_DIR = os.path.join(DATA_ROOT, "meta")
PARCEL_DATA_DIR = os.path.join(DATA_ROOT, "data")
DATES_FILE = os.path.join(META_DIR, "dates.json")
LABELS_FILE = os.path.join(META_DIR, "labels.json")

# Experiment Hyperparameters
S_NUM_SAMPLED_PIXELS = 96
NUM_CHANNELS = 10
NUM_TIME_STEPS = 52
MAX_PIXEL_VALUE = 10000

# Training Hyperparameters
LEARNING_RATE = 1e-3
BATCH_SIZE = 64
NUM_EPOCHS = 100

# Cross-validation
NUM_FOLDS = 5
RANDOM_SEED = 42

# Model Architecture Configurations
pse_config = {
    'mlp1_dims': [NUM_CHANNELS, 32, 64],
    'mlp2_dims': [128, 128]  # Input will be 2 * mlp1_dims[-1] = 2 * 64 = 128
}

transformer_config = {
    'd_model': 128,  # Must match pse_config['mlp2_dims'][-1]
    'n_heads': 8,
    'num_layers': 2,
    'dropout_rate': 0.1
}

classifier_config = {
    'mlp_dims': [128, 64, -1],  # -1 for num_classes to be filled later
    'dropout_rate': 0.1
}

# =============================================================================
# SET DEVICE
# =============================================================================

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# =============================================================================
# LOAD INITIAL DATA
# =============================================================================

# Load dates and convert to day-of-year array
import json
with open(DATES_FILE, 'r') as f:
    date_data = json.load(f)
date_strings = [str(date) for date in date_data]
day_of_year_array = data_utils.get_day_of_year_array(date_strings)
print(f"Day-of-year array shape: {day_of_year_array.shape}")

# Get parcel IDs available on disk
parcel_ids_on_disk = [f.replace('.zarr', '') for f in os.listdir(PARCEL_DATA_DIR) if f.endswith('.zarr')]
print(f"Found {len(parcel_ids_on_disk)} parcels on disk")

# Load and analyze labels
labels_df_analyzed = data_utils.load_and_analyze_labels(LABELS_FILE, parcel_ids_on_disk)
print(f"Labels DataFrame shape: {labels_df_analyzed.shape}")

# Filter labels and reindex categories
filtered_labels_df, label_mapping, NUM_CLASSES = data_utils.filter_and_reindex_labels(
    labels_df_analyzed, min_samples_per_category=200
)
print(f"Number of classes after filtering: {NUM_CLASSES}")
print(f"Filtered labels DataFrame shape: {filtered_labels_df.shape}")

# Update model configurations with actual values
classifier_config['mlp_dims'][-1] = NUM_CLASSES
transformer_config['d_model'] = pse_config['mlp2_dims'][-1]
classifier_config['mlp_dims'][0] = transformer_config['d_model']

print(f"Final model configurations:")
print(f"  PSE config: {pse_config}")
print(f"  Transformer config: {transformer_config}")
print(f"  Classifier config: {classifier_config}")

# Create parcel info list for dataset
all_parcel_info = list(zip(filtered_labels_df['parcel_id'].values, filtered_labels_df['new_reindexed_label'].values))
print(f"Total parcel-label pairs: {len(all_parcel_info)}")

print("\nExperiment setup complete!")

# =============================================================================
# K-FOLD CROSS-VALIDATION LOOP
# =============================================================================

# Initialize K-Fold cross-validator
kfold = KFold(n_splits=NUM_FOLDS, shuffle=True, random_state=RANDOM_SEED)
print(f"Starting {NUM_FOLDS}-fold cross-validation...")

# Initialize storage for results from each fold
fold_results = []  # Will store dict of metrics for each fold

# K-Fold Cross-Validation Loop
for fold_idx, (train_indices, val_indices) in enumerate(kfold.split(all_parcel_info)):
    print(f"\n{'='*60}")
    print(f"--- Fold {fold_idx + 1}/{NUM_FOLDS} ---")
    print(f"{'='*60}")

    # Create train/validation splits for current fold
    current_train_info = [all_parcel_info[i] for i in train_indices]
    current_val_info = [all_parcel_info[i] for i in val_indices]

    print(f"Train samples: {len(current_train_info)}")
    print(f"Validation samples: {len(current_val_info)}")

    # =================================================================
    # FOLD-SPECIFIC SETUP AND TRAINING
    # =================================================================

    # 1. Calculate Normalization Statistics for current train fold
    print("Calculating normalization statistics...")
    rescaler = data_utils.RescalePixels(MAX_PIXEL_VALUE)
    norm_stats = data_utils.calculate_normalization_stats(
        parcel_info_list=current_train_info,
        data_root_path=PARCEL_DATA_DIR,
        num_channels=NUM_CHANNELS,
        rescale_transform=rescaler
    )

    # Convert to tensors and move to device
    norm_stats['mean'] = torch.tensor(norm_stats['mean'])
    norm_stats['std'] = torch.tensor(norm_stats['std'])
    print(f"Normalization stats - Mean: {norm_stats['mean'][:3]}..., Std: {norm_stats['std'][:3]}...")

    # 2. Create Datasets and DataLoaders for train/val
    print("Creating datasets and dataloaders...")
    train_dataset = data_utils.ParcelDataset(
        parcel_info_list=current_train_info,
        data_root_path=PARCEL_DATA_DIR,
        S_num_sampled_pixels=S_NUM_SAMPLED_PIXELS,
        is_train=True,
        num_channels=NUM_CHANNELS,
        num_time_steps=NUM_TIME_STEPS,
        rescale_transform=rescaler,
        normalization_stats=norm_stats
    )

    val_dataset = data_utils.ParcelDataset(
        parcel_info_list=current_val_info,
        data_root_path=PARCEL_DATA_DIR,
        S_num_sampled_pixels=S_NUM_SAMPLED_PIXELS,
        is_train=False,
        num_channels=NUM_CHANNELS,
        num_time_steps=NUM_TIME_STEPS,
        rescale_transform=rescaler,
        normalization_stats=norm_stats
    )

    train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=2,
        pin_memory=True
    )

    val_loader = torch.utils.data.DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=2,
        pin_memory=True
    )

    print(f"Train dataset size: {len(train_dataset)}, Val dataset size: {len(val_dataset)}")

    # 3. Initialize Model, Criterion, Optimizer
    print("Initializing model, criterion, and optimizer...")
    current_model = model.ParcelTimeSeriesClassifier(
        pse_config=pse_config,
        transformer_config=transformer_config,
        classifier_config=classifier_config,
        day_of_year_sequence=day_of_year_array
    ).to(device)

    current_criterion = nn.CrossEntropyLoss()
    current_optimizer = torch.optim.Adam(current_model.parameters(), lr=LEARNING_RATE)

    print(f"Model initialized with {sum(p.numel() for p in current_model.parameters())} parameters")

    # 4. Initialize TorchMetrics Collection for validation
    print("Setting up validation metrics...")
    val_metrics_computer = torchmetrics.MetricCollection({
        'accuracy': torchmetrics.Accuracy(task='multiclass', num_classes=NUM_CLASSES, average='micro'),
        'precision_micro': torchmetrics.Precision(task='multiclass', num_classes=NUM_CLASSES, average='micro'),
        'recall_micro': torchmetrics.Recall(task='multiclass', num_classes=NUM_CLASSES, average='micro'),
        'f1_micro': torchmetrics.F1Score(task='multiclass', num_classes=NUM_CLASSES, average='micro'),
        'precision_weighted': torchmetrics.Precision(task='multiclass', num_classes=NUM_CLASSES, average='weighted'),
        'recall_weighted': torchmetrics.Recall(task='multiclass', num_classes=NUM_CLASSES, average='weighted'),
        'f1_weighted': torchmetrics.F1Score(task='multiclass', num_classes=NUM_CLASSES, average='weighted')
    }).to(device)

    # 5. Training loop over epochs
    print("Starting training...")
    best_val_f1_weighted = -1.0
    best_model_state_dict = None

    for epoch in range(NUM_EPOCHS):
        print(f"\nFold {fold_idx + 1}/{NUM_FOLDS} - Epoch {epoch + 1}/{NUM_EPOCHS}")
        print("-" * 50)

        # Train one epoch
        train_loss, train_metrics_results = engine.train_one_epoch(
            current_model,
            train_loader,
            current_criterion,
            current_optimizer,
            device,
            val_metrics_computer.clone(),
            epoch + 1
        )

        # Validate
        val_loss, val_metrics_results, all_val_preds, all_val_targets = engine.evaluate_model(
            current_model,
            val_loader,
            current_criterion,
            device,
            val_metrics_computer,
            epoch + 1
        )

        # Print progress
        print(f"Train Loss: {train_loss:.4f}")
        print(f"Val Loss: {val_loss:.4f}")
        print(f"Val F1 (weighted): {val_metrics_results['f1_weighted']:.4f}")
        print(f"Val Accuracy: {val_metrics_results['accuracy']:.4f}")

        # Model checkpointing based on best validation F1-weighted
        if val_metrics_results['f1_weighted'] > best_val_f1_weighted:
            best_val_f1_weighted = val_metrics_results['f1_weighted']
            best_model_state_dict = current_model.state_dict().copy()
            torch.save(best_model_state_dict, f'best_model_fold_{fold_idx}.pth')
            print(f"★ New best validation F1 (weighted): {best_val_f1_weighted:.4f}")

    print(f"\nTraining completed for Fold {fold_idx + 1}")
    print(f"Best validation F1 (weighted): {best_val_f1_weighted:.4f}")

    # Load best model state for final evaluation
    if best_model_state_dict is not None:
        current_model.load_state_dict(best_model_state_dict)
        torch.save(current_model.state_dict(), f'final_model_fold_{fold_idx}.pth')
        print("Loaded best model state for final evaluation")

    # Final evaluation on validation set
    print("Performing final validation evaluation...")
    final_val_loss, final_val_metrics, final_all_val_preds, final_all_val_targets = engine.evaluate_model(
        current_model,
        val_loader,
        current_criterion,
        device,
        val_metrics_computer,
        epoch_num=-1
    )

    # 6. Store final validation metrics and confusion matrix for this fold
    print("Storing fold results...")

    # Add fold information to final metrics
    fold_result = {
        'fold_idx': fold_idx,
        'best_val_f1_weighted': best_val_f1_weighted,
        **final_val_metrics  # Unpack all final validation metrics
    }
    fold_results.append(fold_result)

    # Generate and display confusion matrix
    final_preds_cpu = final_all_val_preds.cpu().numpy()
    final_targets_cpu = final_all_val_targets.cpu().numpy()

    cm = confusion_matrix(final_targets_cpu, final_preds_cpu)

    # Plot confusion matrix
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=range(NUM_CLASSES),
                yticklabels=range(NUM_CLASSES))
    plt.title(f'Confusion Matrix - Fold {fold_idx + 1}\nF1 (weighted): {final_val_metrics["f1_weighted"]:.4f}')
    plt.xlabel('Predicted Class')
    plt.ylabel('True Class')
    plt.tight_layout()
    plt.show()

    # Print final metrics summary for this fold
    print(f"\nFold {fold_idx + 1} Final Results:")
    print(f"  Accuracy: {final_val_metrics['accuracy']:.4f}")
    print(f"  F1 (micro): {final_val_metrics['f1_micro']:.4f}")
    print(f"  F1 (weighted): {final_val_metrics['f1_weighted']:.4f}")
    print(f"  Precision (weighted): {final_val_metrics['precision_weighted']:.4f}")
    print(f"  Recall (weighted): {final_val_metrics['recall_weighted']:.4f}")

    print(f"Fold {fold_idx + 1} completed!")

print(f"\n{'='*60}")
print("All folds completed!")
print(f"{'='*60}")

# =============================================================================
# RESULTS AGGREGATION AND ANALYSIS
# =============================================================================

print(f"\n{'='*80}")
print("CROSS-VALIDATION RESULTS SUMMARY")
print(f"{'='*80}")

# =================================================================
# AGGREGATE METRICS ACROSS FOLDS
# =================================================================

# Define the metrics we want to aggregate
metric_keys = [
    'accuracy',
    'f1_micro', 'f1_weighted',
    'precision_micro', 'precision_weighted',
    'recall_micro', 'recall_weighted'
]

# Initialize dictionaries to store aggregated results
aggregated_results = {}

for metric_key in metric_keys:
    # Extract values from all folds (handle both tensor and scalar values)
    metric_values = []
    for fold_result in fold_results:
        value = fold_result[metric_key]
        # Convert tensor to scalar if needed
        if hasattr(value, 'item'):
            metric_values.append(value.item())
        else:
            metric_values.append(float(value))

    # Calculate mean and standard deviation
    mean_value = np.mean(metric_values)
    std_value = np.std(metric_values)

    # Store results
    aggregated_results[metric_key] = {
        'mean': mean_value,
        'std': std_value,
        'values': metric_values
    }

# =================================================================
# DISPLAY AGGREGATED RESULTS
# =================================================================

print(f"\nCross-Validation Results ({NUM_FOLDS} folds):")
print("-" * 60)

# Primary metrics
print(f"{'Metric':<20} {'Mean':<10} {'Std':<10} {'Mean ± Std'}")
print("-" * 60)

for metric_key in metric_keys:
    mean_val = aggregated_results[metric_key]['mean']
    std_val = aggregated_results[metric_key]['std']
    metric_name = metric_key.replace('_', ' ').title()
    print(f"{metric_name:<20} {mean_val:<10.4f} {std_val:<10.4f} {mean_val:.4f} ± {std_val:.4f}")

print("-" * 60)

# Highlight key performance metrics
print(f"\n KEY PERFORMANCE SUMMARY:")
print(f"   Overall Accuracy:     {aggregated_results['accuracy']['mean']:.4f} ± {aggregated_results['accuracy']['std']:.4f}")
print(f"   F1-Score (weighted):  {aggregated_results['f1_weighted']['mean']:.4f} ± {aggregated_results['f1_weighted']['std']:.4f}")
print(f"   F1-Score (micro):     {aggregated_results['f1_micro']['mean']:.4f} ± {aggregated_results['f1_micro']['std']:.4f}")

# =================================================================
# DETAILED FOLD-BY-FOLD BREAKDOWN
# =================================================================

print(f"\n FOLD-BY-FOLD BREAKDOWN:")
print("-" * 80)
print(f"{'Fold':<6} {'Accuracy':<10} {'F1-Weighted':<12} {'F1-Micro':<10} {'Precision-W':<12} {'Recall-W':<10}")
print("-" * 80)

for i, fold_result in enumerate(fold_results):
    acc = fold_result['accuracy'].item() if hasattr(fold_result['accuracy'], 'item') else fold_result['accuracy']
    f1_w = fold_result['f1_weighted'].item() if hasattr(fold_result['f1_weighted'], 'item') else fold_result['f1_weighted']
    f1_m = fold_result['f1_micro'].item() if hasattr(fold_result['f1_micro'], 'item') else fold_result['f1_micro']
    prec_w = fold_result['precision_weighted'].item() if hasattr(fold_result['precision_weighted'], 'item') else fold_result['precision_weighted']
    rec_w = fold_result['recall_weighted'].item() if hasattr(fold_result['recall_weighted'], 'item') else fold_result['recall_weighted']

    print(f"{i+1:<6} {acc:<10.4f} {f1_w:<12.4f} {f1_m:<10.4f} {prec_w:<12.4f} {rec_w:<10.4f}")

print("-" * 80)

# =================================================================
# MODEL STABILITY ANALYSIS
# =================================================================

print(f"\n MODEL STABILITY ANALYSIS:")
print("-" * 40)

# Calculate coefficient of variation (CV) for key metrics
key_stability_metrics = ['accuracy', 'f1_weighted', 'f1_micro']

for metric in key_stability_metrics:
    mean_val = aggregated_results[metric]['mean']
    std_val = aggregated_results[metric]['std']
    cv = (std_val / mean_val) * 100 if mean_val > 0 else 0

    stability_level = "Excellent" if cv < 5 else "Good" if cv < 10 else "Moderate" if cv < 15 else "Poor"
    metric_name = metric.replace('_', ' ').title()

    print(f"{metric_name:<15}: CV = {cv:5.2f}% ({stability_level})")

print(f"\nCV (Coefficient of Variation) Interpretation:")
print(f"  < 5%:  Excellent stability")
print(f"  5-10%: Good stability")
print(f"  10-15%: Moderate stability")
print(f"  > 15%: Poor stability (high variance across folds)")

# =================================================================
# SAVE RESULTS TO FILE (OPTIONAL)
# =================================================================

# Create results summary dictionary
results_summary = {
    'experiment_config': {
        'num_folds': NUM_FOLDS,
        'num_epochs': NUM_EPOCHS,
        'batch_size': BATCH_SIZE,
        'learning_rate': LEARNING_RATE,
        'num_sampled_pixels': S_NUM_SAMPLED_PIXELS,
        'num_classes': NUM_CLASSES
    },
    'aggregated_metrics': aggregated_results,
    'fold_results': fold_results
}

print(f"\n Results summary prepared for saving")
print(f"   Use: import json; json.dump(results_summary, open('cv_results.json', 'w'), default=str)")

print(f"\n{'='*80}")
print("CROSS-VALIDATION ANALYSIS COMPLETE")
print(f"{'='*80}")

import json
json.dump(results_summary, open('/content/drive/MyDrive/Big Data 2/cv_results512.json', 'w'), default=str)